
GET http://localhost:5000/api HTTP/1.1
content-type: application/json

###

POST http://localhost:5000/api/posts HTTP/1.1
content-type: application/json
Authorization: bearer "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoxMjMsIm5hbWUiOiJteU5hbWUiLCJlbWFpbCI6Im15bWFpbEBtYWlsLmNvbSJ9LCJpYXQiOjE2MjI0ODc3MDN9.GdX43CRQlbYcH_YkQGkupflmOOQhGHwFAdn_cx4i2_k"


###

POST http://localhost:5000/api/login HTTP/1.1
content-type: application/json